### ISSUE TITLE
Change title font size

### ISSUE THREAD

**Issue by Zhuohao-Li** [Teddy-van-Jerry/SEU-ML-Assign_LaTeX_Template#3]
I want to change "Machine Learning" to my specific one like "Computer Vision" but I can't find how to customize its font size in .cls. Any solutions?

**Comment by Zhuohao-Li** [comment]
Besides, how to fix the bug when @studentID is too long like this
<img width="143" alt="截屏2022-05-12 21 20 01" src="https://user-images.githubusercontent.com/61313275/168084236-acb88070-5db1-4176-9a2c-df02f3e01879.png">
:

**Comment by Teddy-van-Jerry** [comment]
Please accept my apology that I did not have enough time to carry out further development on the customized design of the template. I will add these futures in the future.

Currently, as a workaround, you may change [Line 328](https://github.com/Teddy-van-Jerry/SEU-ML-Assign_LaTeX_Template/blob/96e888d28248224909e3d9e19109810fa5a2e139/seu-ml-assign.cls#L328) of the `cls` file to change its font size. Information on the command can be found [here](https://tex.stackexchange.com/a/48277/234654). If you have further problems, please also feel free to comment below.

**Comment by Teddy-van-Jerry** [comment]
The `\studentID{}` issue can be resolved by adding `\small` in the field then the font size of the line will be smaller.

**Comment by Teddy-van-Jerry** [comment]
About the studentID issue, I look at it now and reckon you might mean the digit goes 'up and down'. Well, this is what the font Libertine does. You may change the font using the trick I mentioned in issue #2.
